"""SQLite persistence primitives for the generic Multi-Agent Runtime kernel.

The persistence package is intentionally separate from ``runtime_domain``:
domain values remain storage-neutral, while this package owns SQLite schema
versioning and transaction boundaries.  The legacy ``runtime_sqlite`` module
continues to store compatibility snapshots and is not an authoritative Store.
"""

from .sqlite import (
    OutboxPolicy,
    RUNTIME_DB_COMPONENT,
    RUNTIME_DB_SCHEMA_VERSION,
    RuntimeCommitError,
    RuntimeDatabaseBusyError,
    RuntimeDatabaseIntegrityError,
    RuntimeOutboxConfigurationError,
    RuntimePersistenceError,
    RuntimePersistenceFaultPoint,
    RuntimeRollbackError,
    RuntimeSchemaCorruptionError,
    RuntimeSchemaError,
    RuntimeSchemaTooNewError,
    RuntimeSQLiteConfig,
    RuntimeSQLiteConfigurationError,
    RuntimeSQLResult,
    RuntimeTransactionError,
    RuntimeUnitOfWork,
    RuntimeUnitOfWorkState,
    RuntimeUnitOfWorkStateError,
    SQLiteRuntimeDatabase,
)
from .outbox import (
    OutboxClaim,
    OutboxClaimOwnership,
    OutboxClaimTokenFactory,
    OutboxClock,
    OutboxNackErrorCode,
    OutboxNackResult,
    OutboxSnapshot,
    OutboxState,
    RuntimeOutboxAttemptExhaustedError,
    RuntimeOutboxClockError,
    RuntimeOutboxLifecycleError,
    RuntimeOutboxOwnershipLostError,
    RuntimeOutboxTokenFactoryError,
    RuntimeOutboxValidationError,
    SQLiteOutboxLifecycleStore,
)
from .state_event import (
    RuntimeEventConflictError,
    RuntimeEventSequenceConflictError,
    RuntimeIdempotencyConflictError,
    RuntimeStateConflictError,
    RuntimeStateEventConflictError,
    RuntimeStateEventError,
    RuntimeStateEventValidationError,
    RuntimeStoredDataCorruptionError,
    SQLiteThreadEventStore,
    ThreadEventApplyResult,
    ThreadEventMutation,
)

__all__ = [
    "OutboxPolicy",
    "OutboxState",
    "OutboxNackErrorCode",
    "OutboxSnapshot",
    "OutboxClaimOwnership",
    "OutboxClaim",
    "OutboxNackResult",
    "OutboxClock",
    "OutboxClaimTokenFactory",
    "RUNTIME_DB_COMPONENT",
    "RUNTIME_DB_SCHEMA_VERSION",
    "RuntimePersistenceError",
    "RuntimeSQLiteConfigurationError",
    "RuntimeSchemaError",
    "RuntimeSchemaTooNewError",
    "RuntimeSchemaCorruptionError",
    "RuntimeDatabaseIntegrityError",
    "RuntimeOutboxConfigurationError",
    "RuntimeOutboxLifecycleError",
    "RuntimeOutboxValidationError",
    "RuntimeOutboxOwnershipLostError",
    "RuntimeOutboxClockError",
    "RuntimeOutboxTokenFactoryError",
    "RuntimeOutboxAttemptExhaustedError",
    "RuntimeTransactionError",
    "RuntimeDatabaseBusyError",
    "RuntimeUnitOfWorkStateError",
    "RuntimeCommitError",
    "RuntimeRollbackError",
    "RuntimePersistenceFaultPoint",
    "RuntimeUnitOfWorkState",
    "RuntimeSQLiteConfig",
    "RuntimeSQLResult",
    "SQLiteRuntimeDatabase",
    "RuntimeUnitOfWork",
    "RuntimeStateEventError",
    "RuntimeStateEventValidationError",
    "RuntimeStateEventConflictError",
    "RuntimeStateConflictError",
    "RuntimeEventConflictError",
    "RuntimeIdempotencyConflictError",
    "RuntimeEventSequenceConflictError",
    "RuntimeStoredDataCorruptionError",
    "ThreadEventApplyResult",
    "ThreadEventMutation",
    "SQLiteThreadEventStore",
    "SQLiteOutboxLifecycleStore",
]
